import { useEffect, useMemo, useState } from 'react';
import { Check, Clipboard, LogOut, Plus, RefreshCw, Search, Shield, X, Phone } from 'lucide-react';
import { useAuth } from '../../auth/hooks/useAuth';
import { backendJson } from '../../../services/backend/api';
import { backendUrl } from '../../../services/backend/url';
import { getToken } from '../../../services/auth/localAuth';
import { CountryCodeSelect } from '../../../components/forms/CountryCodeSelect';
import { Link } from 'react-router-dom';

interface Client { id: string; tenant_id: string; tenant_name: string; email: string; full_name: string | null; status: string; tenant_status: string; created_at: string }
interface CreatedClient extends Client { temporary_password: string }

const date = (value: string) => new Date(value).toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' });
const active = (client: Client) => client.status === 'active' && client.tenant_status === 'active';

export default function AdminPage() {
  const { user, signOut } = useAuth();
  const [clients, setClients] = useState<Client[]>([]); const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState('');
  const [showAdd, setShowAdd] = useState(false); const [created, setCreated] = useState<CreatedClient | null>(null); const [selected, setSelected] = useState<Client | null>(null); const [pendingStatus, setPendingStatus] = useState<{ client: Client; nextStatus: 'active' | 'suspended' } | null>(null);
  const [form, setForm] = useState({ tenant_name: '', full_name: '', email: '' }); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState('');
  const [showPhone, setShowPhone] = useState(false); const [phoneCode, setPhoneCode] = useState('+91'); const [phoneForm, setPhoneForm] = useState({ phone_number: '', provider: 'omnidimension', provider_phone_number_id: '' }); const [phoneSaving, setPhoneSaving] = useState(false);

  const load = async (initial = false) => { if (initial) setLoading(true); else setRefreshing(true); setError(''); try { setClients(await backendJson<Client[]>('/admin/clients')); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load clients.'); } finally { setLoading(false); setRefreshing(false); } };
  useEffect(() => { const timer = window.setTimeout(() => { void load(true); }, 0); return () => window.clearTimeout(timer); }, []);
  const filtered = useMemo(() => clients.filter(c => `${c.tenant_name} ${c.full_name ?? ''} ${c.email}`.toLowerCase().includes(query.toLowerCase())), [clients, query]);
  const activeCount = clients.filter(active).length;
  const create = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { const result = await backendJson<CreatedClient>('/admin/clients', { method: 'POST', body: JSON.stringify(form) }); setForm({ tenant_name: '', full_name: '', email: '' }); setShowAdd(false); setCreated(result); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to create client.'); } finally { setSaving(false); } };
  const setStatus = async () => { if (!pendingStatus) return; const { client, nextStatus } = pendingStatus; const label = nextStatus === 'active' ? 'activate' : 'deactivate'; setPendingStatus(null); try { await backendJson(`/admin/clients/${client.id}`, { method: 'PATCH', body: JSON.stringify({ status: nextStatus }) }); setNotice(`${client.tenant_name} was ${label}d.`); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to update client.'); } };
  const copyCredentials = async () => { if (!created) return; await navigator.clipboard.writeText(`Email: ${created.email}\nTemporary password: ${created.temporary_password}`); setNotice('Credentials copied. Share them securely with the client.'); };
  const registerPhone = async (event: React.FormEvent) => { event.preventDefault(); setPhoneSaving(true); setError(''); setNotice(''); try { const response = await fetch(backendUrl('/phone-numbers/platform-demo'), { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${getToken() ?? ''}` }, body: JSON.stringify({ ...phoneForm, phone_number: `${phoneCode}${phoneForm.phone_number}`.replace(/[ ()-]/g, '') }) }); const body = await response.json().catch(() => null); if (!response.ok) { const error = new Error(typeof body?.detail === 'string' ? body.detail : 'Unable to register platform phone.') as Error & { status?: number }; error.status = response.status; throw error; } setShowPhone(false); setPhoneForm({ phone_number: '', provider: 'omnidimension', provider_phone_number_id: '' }); setPhoneCode('+91'); setNotice(response.status === 200 ? 'Platform phone already existed/was updated.' : 'Platform phone registered successfully.'); } catch (e) { const status = (e as Error & { status?: number }).status; setError(status === 401 || status === 403 ? 'Authorization error: administrator access is required.' : status === 422 ? 'Validation error: check the phone number and provider ID.' : e instanceof Error ? e.message : 'Unable to register platform phone.'); } finally { setPhoneSaving(false); } };

  return <div className="min-h-screen bg-gray-50 text-gray-900">
    <header className="h-16 bg-white border-b border-gray-200 px-5 lg:px-8 flex items-center justify-between"><div className="flex items-center gap-3"><div className="w-9 h-9 rounded-lg bg-blue-600 text-white font-bold flex items-center justify-center">PC</div><div><div className="font-bold">Pontis</div><div className="text-xs text-gray-500">Admin Portal</div></div></div><div className="flex items-center gap-4"><div className="hidden sm:block text-right"><div className="text-sm font-medium">{user?.email}</div><div className="text-xs text-gray-500">Administrator</div></div><button onClick={() => void signOut()} className="p-2 text-gray-500 hover:text-rose-600" title="Sign out"><LogOut size={18} /></button></div></header>
    <main className="max-w-7xl mx-auto p-5 lg:p-8 space-y-7"><div className="flex items-start justify-between"><div><p className="text-sm text-blue-600 font-medium">Overview</p><h1 className="text-2xl font-bold mt-1">Client management</h1><p className="text-sm text-gray-500 mt-1">Provision and manage Pontis client accounts.</p></div><Link to="/admin/coupons" className="px-3 py-2 bg-blue-600 text-white rounded-lg text-sm">Coupons</Link></div>
      {error && <div className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700 flex justify-between gap-3">{error}<button onClick={() => setError('')}><X size={16} /></button></div>}{notice && <div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</div>}
      <section className="bg-white border border-gray-200 rounded-xl shadow-sm p-5 flex items-center justify-between"><div><h2 className="font-semibold">Platform phone</h2><p className="text-sm text-gray-500 mt-1">Register an already-owned provider number for authenticated tenants.</p></div><button onClick={() => setShowPhone(true)} className="px-3 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium flex items-center gap-2"><Phone size={16} /> Register platform phone</button></section>
      <section className="grid sm:grid-cols-3 gap-4">{[['Total clients', clients.length, 'text-blue-600'], ['Active clients', activeCount, 'text-emerald-600'], ['Inactive clients', clients.length - activeCount, 'text-amber-600']].map(([label, value, color]) => <div key={String(label)} className="bg-white border border-gray-200 rounded-xl p-5 shadow-sm"><div className="text-sm text-gray-500">{label}</div><div className={`text-3xl font-bold mt-2 ${color}`}>{value}</div></div>)}</section>
      <section className="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden"><div className="p-5 border-b border-gray-200 flex flex-col sm:flex-row gap-3 sm:items-center sm:justify-between"><div><h2 className="font-semibold">Clients</h2><p className="text-sm text-gray-500 mt-1">Tenant accounts and primary contacts</p></div><div className="flex gap-2"><div className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" /><input aria-label="Search clients" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search clients" className="pl-9 pr-3 py-2 border rounded-lg text-sm w-52" /></div><button onClick={() => void load()} className="p-2 border rounded-lg text-gray-500 hover:bg-gray-50" title="Refresh"><RefreshCw size={17} className={refreshing ? 'animate-spin' : ''} /></button><button onClick={() => setShowAdd(true)} className="px-3 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium flex items-center gap-2"><Plus size={16} /> Add client</button></div></div>
        {loading ? <div className="p-12 text-center text-sm text-gray-500">Loading clients...</div> : filtered.length === 0 ? <div className="p-12 text-center"><Shield className="mx-auto text-gray-300" size={28} /><p className="font-medium mt-3">{clients.length ? 'No clients match your search' : 'No clients yet'}</p><p className="text-sm text-gray-500 mt-1">{clients.length ? 'Try a different search.' : 'Add your first client to get started.'}</p></div> : <div className="overflow-x-auto"><table className="w-full text-left"><thead className="bg-gray-50 text-xs uppercase tracking-wide text-gray-500"><tr><th className="px-5 py-3">Client</th><th className="px-5 py-3">Primary contact</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Created</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-gray-100">{filtered.map(client => <tr key={client.id} className="hover:bg-gray-50"><td className="px-5 py-4"><button onClick={() => setSelected(client)} className="font-medium hover:text-blue-600 text-left">{client.tenant_name}</button><div className="text-xs text-gray-400 mt-1">{client.tenant_id.slice(0, 8)}...</div></td><td className="px-5 py-4"><div className="text-sm">{client.full_name || '—'}</div><div className="text-xs text-gray-500">{client.email}</div></td><td className="px-5 py-4"><span className={`inline-flex px-2 py-1 rounded-full text-xs font-medium ${active(client) ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{active(client) ? 'Active' : 'Inactive'}</span></td><td className="px-5 py-4 text-sm text-gray-500">{date(client.created_at)}</td><td className="px-5 py-4 text-right"><button onClick={() => setSelected(client)} className="text-sm text-blue-600 hover:underline mr-4">View</button><button onClick={() => setPendingStatus({ client, nextStatus: active(client) ? 'suspended' : 'active' })} className="text-sm text-gray-500 hover:text-rose-600">{active(client) ? 'Deactivate' : 'Activate'}</button></td></tr>)}</tbody></table></div>}
      </section>
    </main>
    {showAdd && <div className="fixed inset-0 bg-black/30 flex items-center justify-center p-4 z-50"><form onSubmit={create} className="bg-white rounded-xl shadow-xl w-full max-w-md p-6"><div className="flex justify-between items-center"><h2 className="text-lg font-semibold">Add client</h2><button type="button" onClick={() => setShowAdd(false)}><X size={18} /></button></div><p className="text-sm text-gray-500 mt-1">A temporary password will be generated securely.</p><div className="space-y-4 mt-5">{([['tenant_name', 'Company / tenant name'], ['full_name', 'Primary contact name'], ['email', 'Email address']] as const).map(([key, label]) => <label key={key} className="block text-sm font-medium">{label}<input required={key !== 'full_name'} type={key === 'email' ? 'email' : 'text'} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} className="mt-1 w-full border rounded-lg px-3 py-2 font-normal" /></label>)}</div><div className="flex justify-end gap-2 mt-6"><button type="button" onClick={() => setShowAdd(false)} className="px-4 py-2 text-sm">Cancel</button><button disabled={saving} className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm disabled:opacity-60">{saving ? 'Creating...' : 'Create client'}</button></div></form></div>}
    {created && <div className="fixed inset-0 bg-black/30 flex items-center justify-center p-4 z-50"><div className="bg-white rounded-xl shadow-xl w-full max-w-md p-6"><div className="w-10 h-10 rounded-full bg-emerald-100 text-emerald-600 flex items-center justify-center"><Check size={20} /></div><h2 className="text-lg font-semibold mt-4">Client created successfully</h2><p className="text-sm text-gray-500 mt-1">Save these credentials now. The temporary password will not be shown again.</p><div className="bg-gray-50 rounded-lg p-4 mt-5 text-sm space-y-3"><div><span className="text-gray-500">Email</span><div className="font-medium">{created.email}</div></div><div><span className="text-gray-500">Temporary password</span><div className="font-mono font-medium break-all">{created.temporary_password}</div></div></div><p className="text-xs text-amber-700 mt-4">The client must change this password on first login.</p><div className="flex gap-2 mt-6"><button onClick={() => void copyCredentials()} className="flex-1 border rounded-lg px-3 py-2 text-sm flex items-center justify-center gap-2"><Clipboard size={16} /> Copy credentials</button><button onClick={() => setCreated(null)} className="flex-1 bg-blue-600 text-white rounded-lg px-3 py-2 text-sm">Done</button></div></div></div>}
    {selected && <div className="fixed inset-0 bg-black/30 flex items-center justify-center p-4 z-50"><div className="bg-white rounded-xl shadow-xl w-full max-w-md p-6"><div className="flex justify-between"><div><p className="text-xs text-blue-600 font-medium">Client details</p><h2 className="text-xl font-semibold mt-1">{selected.tenant_name}</h2></div><button onClick={() => setSelected(null)}><X size={18} /></button></div><dl className="mt-6 space-y-4 text-sm"><div><dt className="text-gray-500">Primary contact</dt><dd className="font-medium mt-1">{selected.full_name || '—'}</dd></div><div><dt className="text-gray-500">Email</dt><dd className="font-medium mt-1">{selected.email}</dd></div><div><dt className="text-gray-500">Status</dt><dd className="font-medium mt-1">{active(selected) ? 'Active' : 'Inactive'}</dd></div><div><dt className="text-gray-500">Created</dt><dd className="font-medium mt-1">{date(selected.created_at)}</dd></div></dl><button onClick={() => setSelected(null)} className="w-full mt-7 border rounded-lg py-2 text-sm">Close</button></div></div>}
    {pendingStatus && <div className="fixed inset-0 bg-black/30 flex items-center justify-center p-4 z-50"><div className="bg-white rounded-xl shadow-xl w-full max-w-md p-6"><h2 className="text-lg font-semibold">{pendingStatus.nextStatus === 'active' ? 'Activate this client?' : 'Deactivate this client?'}</h2><p className="text-sm text-gray-500 mt-2">{pendingStatus.nextStatus === 'active' ? "This will restore the client's ability to log in." : 'This will prevent the client from logging in until the account is activated again.'}</p><div className="flex justify-end gap-2 mt-6"><button onClick={() => setPendingStatus(null)} className="px-4 py-2 text-sm">Cancel</button><button onClick={() => void setStatus()} className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm">{pendingStatus.nextStatus === 'active' ? 'Activate' : 'Deactivate'}</button></div></div></div>}
    {showPhone && <div className="fixed inset-0 bg-black/30 flex items-center justify-center p-4 z-50"><form onSubmit={registerPhone} className="bg-white rounded-xl shadow-xl w-full max-w-md p-6"><div className="flex justify-between items-center"><h2 className="text-lg font-semibold">Register platform phone</h2><button type="button" onClick={() => setShowPhone(false)}><X size={18} /></button></div><p className="text-sm text-gray-500 mt-1">No provider purchase or provisioning is performed.</p><div className="space-y-4 mt-5"><label className="block text-sm font-medium">Phone number<div className="mt-1 flex gap-2"><CountryCodeSelect value={phoneCode} onChange={setPhoneCode} disabled={phoneSaving} /><input required pattern="[0-9 ()-]{7,20}" value={phoneForm.phone_number} onChange={e => setPhoneForm({ ...phoneForm, phone_number: e.target.value })} placeholder="98765 43210" className="w-full border rounded-lg px-3 py-2 font-normal" /></div></label><label className="block text-sm font-medium">Provider<select value={phoneForm.provider} onChange={e => setPhoneForm({ ...phoneForm, provider: e.target.value })} className="mt-1 w-full border rounded-lg px-3 py-2 font-normal"><option value="omnidimension">omnidimension</option></select></label><label className="block text-sm font-medium">Provider phone number ID<input required value={phoneForm.provider_phone_number_id} onChange={e => setPhoneForm({ ...phoneForm, provider_phone_number_id: e.target.value })} className="mt-1 w-full border rounded-lg px-3 py-2 font-normal" /></label></div><div className="flex justify-end gap-2 mt-6"><button type="button" onClick={() => setShowPhone(false)} className="px-4 py-2 text-sm">Cancel</button><button disabled={phoneSaving} className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm disabled:opacity-60">{phoneSaving ? 'Registering...' : 'Register phone'}</button></div></form></div>}
  </div>;
}


