import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { backendJson } from '../../../services/backend/api';

type Coupon = { id:string; code:string; title:string; description?:string; discount_type:string; promotional_minutes?:number; starts_at?:string; expires_at?:string; usage_limit?:number; is_active:boolean; status:string };
const empty = { code:'', title:'', description:'', promotional_minutes:'', starts_at:'', expires_at:'', usage_limit:'' };
export default function CouponsPage() {
  const [items,setItems]=useState<Coupon[]>([]); const [form,setForm]=useState(empty); const [query,setQuery]=useState(''); const [error,setError]=useState('');
  const load=async()=>setItems(await backendJson<Coupon[]>('/admin/coupons')); useEffect(()=>{void load()},[]);
  const save=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{await backendJson('/admin/coupons',{method:'POST',body:JSON.stringify({...form,discount_value:0,promotional_minutes:Number(form.promotional_minutes),usage_limit:form.usage_limit?Number(form.usage_limit):null,starts_at:form.starts_at?new Date(form.starts_at).toISOString():null,expires_at:form.expires_at?new Date(form.expires_at).toISOString():null})});setForm(empty);await load()}catch(x){setError(x instanceof Error?x.message:'Unable to save coupon')}};
  const toggle=async(c:Coupon)=>{await backendJson(`/admin/coupons/${c.id}/${c.is_active?'deactivate':'activate'}`,{method:'POST'});await load()};
  const shareCoupon=async(c:Coupon)=>{const customers=await backendJson<Array<{tenant_id:string;tenant_name:string}>>('/admin/clients');const answer=window.prompt(`Share ${c.code} with customers (comma-separated numbers):\n${customers.map((x,i)=>`${i+1}. ${x.tenant_name}`).join('\n')}`);if(!answer)return;const ids=answer.split(',').map(x=>customers[Number(x.trim())-1]?.tenant_id).filter(Boolean);if(ids.length)await backendJson(`/admin/coupons/${c.id}/share`,{method:'POST',body:JSON.stringify({tenant_ids:ids})});};
  return <main className="min-h-screen bg-gray-50 p-5 lg:p-8"><div className="max-w-7xl mx-auto"><Link to="/admin" className="text-sm text-blue-600">← Admin portal</Link><h1 className="text-2xl font-bold mt-4">Coupons</h1><p className="text-sm text-gray-500 mt-1">Create and manage promotional calling-minute offers.</p>{error&&<div className="mt-4 p-3 bg-rose-50 text-rose-700 rounded">{error}</div>}<form onSubmit={save} className="bg-white border rounded-xl p-5 mt-6 grid md:grid-cols-4 gap-3">{[['code','Code'],['title','Title'],['description','Description'],['promotional_minutes','Promotional minutes'],['starts_at','Starts at'],['expires_at','Expires at'],['usage_limit','Usage limit']].map(([k,l])=><label className="text-sm" key={k}>{l}<input required={k==='code'||k==='title'||k==='promotional_minutes'} type={k.includes('at')?'datetime-local':k.includes('minutes')||k==='usage_limit'?'number':'text'} value={form[k as keyof typeof form]} onChange={e=>setForm({...form,[k]:e.target.value})} className="mt-1 w-full border rounded-lg px-3 py-2" /></label>)}<button className="bg-blue-600 text-white rounded-lg px-4 py-2 self-end">Create coupon</button></form><div className="bg-white border rounded-xl mt-6 overflow-auto"><div className="p-4 border-b"><input placeholder="Search coupons" value={query} onChange={e=>setQuery(e.target.value)} className="border rounded-lg px-3 py-2" /></div><table className="w-full text-left text-sm"><thead className="bg-gray-50"><tr>{['Code','Title','Reward','Dates','Usage','Status',''].map(x=><th className="px-4 py-3" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y">{items.filter(c=>`${c.code} ${c.title}`.toLowerCase().includes(query.toLowerCase())).map(c=><tr key={c.id}><td className="px-4 py-3 font-mono">{c.code}</td><td className="px-4 py-3">{c.title}</td><td className="px-4 py-3">{c.promotional_minutes} free minutes</td><td className="px-4 py-3">{c.starts_at?new Date(c.starts_at).toLocaleDateString():'Now'} – {c.expires_at?new Date(c.expires_at).toLocaleDateString():'No expiry'}</td><td className="px-4 py-3">0{c.usage_limit?` / ${c.usage_limit}`:''}</td><td className="px-4 py-3 capitalize">{c.status}</td><td className="px-4 py-3"><button onClick={()=>void toggle(c)} className="text-blue-600">{c.is_active?'Deactivate':'Activate'}</button></td></tr>)}</tbody></table></div></div></main>;
}
