import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Check, FileText, Loader2, MessageCircle, Sparkles } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { backendJson } from '../../../services/backend/api';

const languages = ['English', 'Hindi', 'Telugu', 'Tamil', 'Kannada', 'Malayalam', 'Marathi', 'Bengali', 'Gujarati', 'Punjabi', 'Odia', 'Assamese'];
type Placeholder = { key: string; label: string; description: string; type: string; required: boolean };
type Template = { id: string; name: string; category: string; short_description: string; template_version: number; placeholders: Placeholder[]; purpose: string };
type Voice = { id: string; name: string; tier: string; gender: string };
type Session = { messages: Array<{ role: string; content: string }>; current_question: string | null; answers: Array<{ question: string; answer: string }>; is_complete: boolean };
type Employee = { id: string; name: string; configuration?: Record<string, unknown> | null };

export default function CreateEmployee() {
  const navigate = useNavigate(); const { id } = useParams();
  const [step, setStep] = useState(1); const [name, setName] = useState(''); const [templates, setTemplates] = useState<Template[]>([]);
  const [template, setTemplate] = useState<Template | null>(null); const [values, setValues] = useState<Record<string, string>>({});
  const [mode, setMode] = useState<'chat' | 'prompt'>('chat'); const [prompt, setPrompt] = useState(''); const [language, setLanguage] = useState('');
  const [voices, setVoices] = useState<Voice[]>([]); const [voiceId, setVoiceId] = useState(''); const [employeeId, setEmployeeId] = useState(id ?? '');
  const [session, setSession] = useState<Session | null>(null); const [answer, setAnswer] = useState(''); const [finalPrompt, setFinalPrompt] = useState('');
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { void backendJson<Template[]>('/employees/templates').then(setTemplates).catch(() => setError('Templates could not be loaded.')); void backendJson<Voice[]>('/employees/voice-catalog').then(setVoices).catch(() => setError('Voice catalog could not be loaded.')); }, []);
  useEffect(() => { if (!id || !templates.length) return; void (async () => { try { const e = await backendJson<Employee>(`/employees/${id}`); const c = e.configuration ?? {}; setEmployeeId(e.id); setName(e.name); setLanguage(String(c.language ?? '')); setPrompt(String(c.direct_prompt ?? '')); setMode(c.creation_mode === 'prompt' ? 'prompt' : 'chat'); const t = templates.find(item => item.id === c.selected_template_id); if (t) { setTemplate(t); setValues((c.template_values as Record<string, string>) ?? {}); } setStep(4); setFinalPrompt(String(c.final_prompt ?? '')); } catch { setError('Unable to resume this employee.'); } })(); }, [id, templates]);
  const requiredComplete = useMemo(() => Boolean(template && template.placeholders.every(p => !p.required || values[p.key]?.trim())), [template, values]);
  const canStep1 = name.trim().length > 0 && Boolean(template); const canStep3 = mode === 'chat' || prompt.trim().length >= 20;
  const saveDraft = async (nextStep: number) => { setBusy(true); setError(''); try { let eid = employeeId; if (!eid) { const e = await backendJson<Employee>('/employees', { method: 'POST', body: JSON.stringify({ name: name.trim(), language: language || 'Telugu', creation_mode: mode, selected_template_id: template?.id, selected_template_version: template?.template_version, template_values: values, ...(mode === 'prompt' ? { direct_prompt: prompt } : {}) }) }); eid = e.id; setEmployeeId(eid); window.history.replaceState(null, '', `/employees/${eid}`); } await backendJson(`/employees/${eid}`, { method: 'PATCH', body: JSON.stringify({ name: name.trim(), creation_mode: mode, configuration: { name: name.trim(), language, creation_mode: mode, selected_template_id: template?.id, selected_template_version: template?.template_version, template_values: values, ...(mode === 'prompt' ? { direct_prompt: prompt } : {}) } }) }); setStep(nextStep); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save this draft.'); } finally { setBusy(false); } };
  const startChat = async () => { if (!employeeId) return; setBusy(true); try { const s = await backendJson<Session>(`/employees/${employeeId}/interview/start`, { method: 'POST', body: '{}' }); setSession(s); setStep(3); } catch { setError('Shabdha could not be started.'); } finally { setBusy(false); } };
  const prepareReview = async () => { if (!employeeId) return; const e = await backendJson<Employee>(`/employees/${employeeId}/draft`); const c = e.configuration ?? {}; setFinalPrompt(String(c.final_prompt ?? '')); setLanguage(String(c.language ?? language)); setStep(4); };
  const submitAnswer = async () => { if (!employeeId || !session?.current_question || !answer.trim()) return; setBusy(true); try { const s = await backendJson<Session>(`/employees/${employeeId}/interview/answer`, { method: 'POST', body: JSON.stringify({ question: session.current_question, answer }) }); setSession(s); setAnswer(''); if (s.is_complete) await prepareReview(); } catch { setError('Shabdha could not save that answer.'); } finally { setBusy(false); } };
  const build = async () => { if (!employeeId || !language || !voiceId || !finalPrompt.trim()) return; setBusy(true); try { await backendJson(`/employees/${employeeId}`, { method: 'PATCH', body: JSON.stringify({ configuration: { name: name.trim(), language, creation_mode: mode, selected_template_id: template?.id, selected_template_version: template?.template_version, template_values: values, final_prompt: finalPrompt, voice: { id: voiceId, name: voices.find(v => v.id === voiceId)?.name }, ...(mode === 'prompt' ? { direct_prompt: prompt } : {}) } }) }); await backendJson(`/employees/${employeeId}/publish`, { method: 'POST' }); navigate('/employees'); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to build employee.'); } finally { setBusy(false); } };
  const back = () => step === 1 ? navigate('/employees') : setStep(step - 1); const progress = ['Template & name', 'Business details', 'Build method', 'Review & build'];
  return <main className="flex-1 overflow-y-auto bg-slate-50"><div className="mx-auto max-w-6xl p-6 lg:p-10"><button onClick={back} className="mb-7 flex items-center gap-2 text-sm text-slate-500 hover:text-slate-900"><ArrowLeft size={16} /> Back</button><header className="mb-8"><p className="text-sm font-semibold text-blue-600">Create your AI Employee</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">Build a helpful voice employee</h1><div className="mt-7 grid grid-cols-4 gap-2">{progress.map((label, i) => <div key={label} className="flex items-center gap-2 text-xs font-medium"><span className={`grid h-7 w-7 place-items-center rounded-full ${step > i + 1 ? 'bg-emerald-500 text-white' : step === i + 1 ? 'bg-blue-600 text-white' : 'bg-white text-slate-400 ring-1 ring-slate-200'}`}>{step > i + 1 ? <Check size={14} /> : i + 1}</span><span className={step === i + 1 ? 'text-slate-900' : 'hidden text-slate-400 sm:block'}>{label}</span></div>)}</div></header>
  {step === 1 && <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:p-8"><p className="text-xs font-bold uppercase tracking-widest text-slate-400">Step 1 of 4</p><h2 className="mt-2 text-2xl font-bold text-slate-950">Choose a name and template</h2><label className="mt-8 block text-sm font-semibold text-slate-700">Employee name<input value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Charan" className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal outline-none focus:border-blue-500" /></label><div className="mt-8"><h3 className="text-sm font-semibold text-slate-700">Select one template <span className="text-rose-500">*</span></h3><div className="mt-3 grid gap-3 md:grid-cols-2">{templates.map(t => <button key={t.id} onClick={() => { setTemplate(t); setValues(v => Object.fromEntries(t.placeholders.map(p => [p.key, v[p.key] ?? '']))); }} className={`rounded-xl border p-4 text-left ${template?.id === t.id ? 'border-blue-500 bg-blue-50 ring-2 ring-blue-100' : 'border-slate-200 hover:border-blue-300'}`}><span className="text-xs font-bold uppercase tracking-wider text-blue-600">{t.category}</span><h3 className="mt-1 font-semibold text-slate-900">{t.name}</h3><p className="mt-1 text-sm text-slate-500">{t.short_description}</p></button>)}</div></div><button disabled={!canStep1 || busy} onClick={() => setStep(2)} className="mt-8 rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">Continue</button></section>}
  {step === 2 && template && <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:p-8"><p className="text-xs font-bold uppercase tracking-widest text-slate-400">Step 2 of 4</p><h2 className="mt-2 text-2xl font-bold text-slate-950">Tell us about {template.name}</h2><p className="mt-2 text-sm text-slate-500">These details come from the selected template and help your employee give accurate answers.</p><div className="mt-8 grid gap-5 md:grid-cols-2">{template.placeholders.map(p => <label key={p.key} className="text-sm font-semibold text-slate-700">{p.label} {p.required && <span className="text-rose-500">*</span>}<span className="mt-1 block text-xs font-normal text-slate-500">{p.description}</span><textarea value={values[p.key] ?? ''} onChange={e => setValues(v => ({ ...v, [p.key]: e.target.value }))} rows={p.type === 'textarea' ? 4 : 2} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-blue-500" /></label>)}</div><button disabled={!requiredComplete || busy} onClick={() => void saveDraft(3).then(() => mode === 'chat' ? startChat() : undefined)} className="mt-8 rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">Continue</button></section>}
  {step === 3 && <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:p-8"><p className="text-xs font-bold uppercase tracking-widest text-slate-400">Step 3 of 4</p><h2 className="mt-2 text-2xl font-bold text-slate-950">How do you want to build the employee?</h2><div className="mt-7 grid gap-4 md:grid-cols-2"><button onClick={() => setMode('chat')} className={`rounded-xl border p-5 text-left ${mode === 'chat' ? 'border-blue-500 bg-blue-50' : 'border-slate-200'}`}><MessageCircle className="text-blue-600" size={20} /><h3 className="mt-3 font-semibold">Chat with Shabdha</h3><p className="mt-1 text-sm text-slate-500">Answer a few questions and Shabdha will help build the employee using your selected template.</p></button><button onClick={() => setMode('prompt')} className={`rounded-xl border p-5 text-left ${mode === 'prompt' ? 'border-blue-500 bg-blue-50' : 'border-slate-200'}`}><FileText className="text-blue-600" size={20} /><h3 className="mt-3 font-semibold">Direct Prompt</h3><p className="mt-1 text-sm text-slate-500">Already have the instructions? Paste your complete prompt directly.</p></button></div>{mode === 'prompt' && <textarea value={prompt} onChange={e => setPrompt(e.target.value)} placeholder="Paste your complete employee instructions" className="mt-6 min-h-64 w-full rounded-xl border border-slate-200 p-4 text-sm leading-6 outline-none focus:border-blue-500" />}{mode === 'chat' && session && <div className="mt-6 rounded-xl bg-slate-50 p-5"><div className="max-h-72 space-y-3 overflow-y-auto">{session.messages.map((m, i) => <p key={i} className={`rounded-lg p-3 text-sm ${m.role === 'assistant' ? 'bg-white text-slate-700' : 'ml-8 bg-blue-600 text-white'}`}>{m.content}</p>)}</div>{session.current_question && <div className="mt-4 flex gap-2"><input value={answer} onChange={e => setAnswer(e.target.value)} onKeyDown={e => e.key === 'Enter' && void submitAnswer()} placeholder="Type your answer" className="min-w-0 flex-1 rounded-xl border border-slate-200 px-3 py-2" /><button onClick={() => void submitAnswer()} disabled={busy || !answer.trim()} className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Send</button></div>}</div>}{mode === 'prompt' && <button disabled={!canStep3 || busy} onClick={() => void saveDraft(4).then(prepareReview)} className="mt-8 rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">Continue</button>}</section>}
  {step === 4 && <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:p-8"><p className="text-xs font-bold uppercase tracking-widest text-slate-400">Step 4 of 4</p><h2 className="mt-2 text-2xl font-bold text-slate-950">Review &amp; build</h2><div className="mt-6 grid gap-4 rounded-xl bg-slate-50 p-5 sm:grid-cols-2"><div><p className="text-xs font-semibold uppercase text-slate-400">Employee</p><p className="mt-1 font-semibold">{name}</p></div><div><p className="text-xs font-semibold uppercase text-slate-400">Template</p><p className="mt-1 font-semibold">{template?.name ?? 'Selected template'}</p></div></div><div className="mt-7 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Language<select value={language} onChange={e => setLanguage(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 font-normal"><option value="">Select language</option>{languages.map(l => <option key={l}>{l}</option>)}</select></label><label className="text-sm font-semibold">Voice<select value={voiceId} onChange={e => setVoiceId(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 font-normal"><option value="">Select voice</option>{voices.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label></div><label className="mt-7 block text-sm font-semibold">Complete Employee Prompt<span className="mt-1 block text-xs font-normal text-slate-500">This is the canonical configuration used to build your employee.</span><textarea value={finalPrompt} onChange={e => setFinalPrompt(e.target.value)} className="mt-3 min-h-96 w-full rounded-xl border border-slate-200 p-4 font-mono text-xs leading-5 outline-none focus:border-blue-500" /></label><button disabled={busy || !language || !voiceId || !finalPrompt.trim()} onClick={() => void build()} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">{busy ? <Loader2 size={16} className="animate-spin" /> : <Sparkles size={16} />} Build Employee</button></section>}
  {error && <p className="mt-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}</div></main>;
}
