import { useEffect, useState } from 'react';
import { Plus, Trash2, Upload, X } from 'lucide-react';
import { backendJson } from '../../../services/backend/api';
import type { Config } from '../pages/EmployeeWorkspace';

type Variable = { key: string; label: string; description: string; type: string; required: boolean };
type KnowledgeFile = { id: string; filename: string; file_size: number; status: string; error_message?: string | null };
const types = ['text', 'number', 'phone', 'email', 'date', 'datetime', 'boolean'];

export default function WorkspaceExtensions({ employeeId, config, onChange }: { employeeId: string; config: Config; onChange: (next: Config) => void }) {
  const [stepTitle, setStepTitle] = useState(''); const [stepContent, setStepContent] = useState('');
  const [variableOpen, setVariableOpen] = useState(false); const [files, setFiles] = useState<KnowledgeFile[]>([]); const [error, setError] = useState('');
  const [variable, setVariable] = useState<Variable>({ key: '', label: '', description: '', type: 'text', required: false });
  const steps = config.custom_sections ?? []; const variables = config.conversation_variables ?? [];
  const loadFiles = async () => { try { setFiles(await backendJson<KnowledgeFile[]>(`/employees/${employeeId}/knowledge-files`)); } catch { setError('Knowledge Base could not be loaded.'); } };
  useEffect(() => { const timer = window.setTimeout(() => void loadFiles(), 0); return () => window.clearTimeout(timer); }, [employeeId]);
  const addStep = () => { const title = stepTitle.trim(), content = stepContent.trim(); if (!title || !content || steps.some(s => s.title.toLowerCase() === title.toLowerCase())) return; onChange({ ...config, custom_sections: [...steps, { key: `custom_${Date.now()}`, title, content }] }); setStepTitle(''); setStepContent(''); };
  const saveVariable = () => { const key = variable.key.trim().toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, ''); if (!variable.label.trim() || !key || variables.some(v => v.key === key)) { setError('Variable label and a unique snake_case key are required.'); return; } onChange({ ...config, conversation_variables: [...variables, { ...variable, key, label: variable.label.trim() }] }); setVariable({ key: '', label: '', description: '', type: 'text', required: false }); setVariableOpen(false); };
  const upload = async (file: File) => { const body = new FormData(); body.append('file', file); setError(''); try { const added = await backendJson<KnowledgeFile>(`/employees/${employeeId}/knowledge-files`, { method: 'POST', body }); setFiles(current => [...current, added]); } catch { setError('Knowledge Base upload failed.'); } };
  const removeFile = async (file: KnowledgeFile) => { try { await backendJson(`/employees/${employeeId}/knowledge-files/${file.id}`, { method: 'DELETE' }); setFiles(current => current.filter(item => item.id !== file.id)); } catch { setError('Knowledge Base file could not be removed.'); } };
  const size = (bytes: number) => `${(bytes / 1024 / 1024).toFixed(2)} MB`;
  return <section className="mt-6 space-y-6"><div><h3 className="mb-3 text-sm font-bold uppercase tracking-widest text-slate-400">Custom script sections</h3>{steps.map((step, index) => <div key={step.key} className="mb-3 rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-wider text-blue-600">{index + 7}. {step.title}</span><button onClick={() => onChange({ ...config, custom_sections: steps.filter(s => s.key !== step.key) })} className="text-rose-600"><Trash2 size={15} /></button></div><textarea value={step.content} onChange={e => onChange({ ...config, custom_sections: steps.map(s => s.key === step.key ? { ...s, content: e.target.value } : s) })} rows={3} className="mt-2 w-full rounded-lg border border-slate-200 p-2 text-sm" /></div>)}<div className="rounded-xl border border-dashed border-blue-300 p-4"><h3 className="font-semibold">+ Add a step</h3><div className="mt-3 grid gap-2 sm:grid-cols-2"><input value={stepTitle} onChange={e => setStepTitle(e.target.value)} placeholder="Step title" className="rounded-lg border border-slate-200 px-3 py-2 text-sm" /><input value={stepContent} onChange={e => setStepContent(e.target.value)} placeholder="Instructions" className="rounded-lg border border-slate-200 px-3 py-2 text-sm" /></div><button onClick={addStep} className="mt-3 rounded-lg bg-blue-600 px-3 py-2 text-xs font-semibold text-white"><Plus size={14} className="mr-1 inline" /> Add step</button></div></div>
    <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-bold">Conversation Variables</h2><p className="mt-1 text-sm text-slate-500">Details your employee can collect from each conversation.</p></div><button onClick={() => setVariableOpen(true)} className="rounded-lg border border-slate-300 px-3 py-2 text-xs font-semibold">+ Add variable</button></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{variables.map(v => <div key={v.key} className="rounded-xl border border-blue-100 bg-blue-50 px-3 py-2 text-sm"><div className="flex items-center justify-between gap-2 font-semibold">{v.label}<button onClick={() => onChange({ ...config, conversation_variables: variables.filter(x => x.key !== v.key) })}><X size={14} /></button></div><span className="font-mono text-xs text-slate-500">{v.key} · {v.type}{v.required ? ' · required' : ''}</span><p className="mt-1 text-xs text-slate-500">{v.description}</p></div>)}</div>{variableOpen && <div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="grid gap-2 sm:grid-cols-2"><input value={variable.label} onChange={e => setVariable({ ...variable, label: e.target.value })} placeholder="Label" className="rounded-lg border border-slate-200 px-3 py-2 text-sm" /><input value={variable.key} onChange={e => setVariable({ ...variable, key: e.target.value })} placeholder="snake_case key" className="rounded-lg border border-slate-200 px-3 py-2 text-sm" /><input value={variable.description} onChange={e => setVariable({ ...variable, description: e.target.value })} placeholder="Description" className="rounded-lg border border-slate-200 px-3 py-2 text-sm" /><select value={variable.type} onChange={e => setVariable({ ...variable, type: e.target.value })} className="rounded-lg border border-slate-200 px-3 py-2 text-sm">{types.map(type => <option key={type}>{type}</option>)}</select></div><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={variable.required} onChange={e => setVariable({ ...variable, required: e.target.checked })} /> Required</label><button onClick={saveVariable} className="mt-3 rounded-lg bg-blue-600 px-3 py-2 text-xs font-semibold text-white">Save variable</button></div>}</div>
    <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Knowledge Base</h2><p className="mt-1 text-sm text-slate-500">Give your AI employee the information it needs to answer customer questions.</p><label className="mt-4 inline-flex cursor-pointer items-center gap-2 rounded-lg bg-blue-600 px-3 py-2 text-sm font-semibold text-white"><Upload size={15} /> Upload PDF<input type="file" accept="application/pdf,.pdf" className="hidden" onChange={e => { const file = e.target.files?.[0]; if (file) void upload(file); e.currentTarget.value = ''; }} /></label><div className="mt-4 space-y-2">{files.length ? files.map(file => <div key={file.id} className="flex items-center justify-between rounded-xl border border-slate-200 px-3 py-2 text-sm"><span><strong>{file.filename}</strong><span className="ml-2 text-xs text-slate-500">{size(file.file_size)}</span><span className={`ml-2 text-xs ${file.status === 'ready' ? 'text-emerald-700' : 'text-amber-700'}`}>● {file.status}</span></span><button onClick={() => void removeFile(file)} className="text-rose-600"><Trash2 size={15} /></button></div>) : <p className="text-sm text-slate-500">No knowledge files yet. Upload product catalogs, FAQs, pricing documents, or policies.</p>}</div></div>{error && <p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}</section>;
}
